included:
  - ios-app-template
  - ios-app-templateTests
  - ios-app-templateUITests

disabled_rules:
  - line_length
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - redundant_nil_coalescing
